services/api/website/__init__.py
from os.path import exists

from flask import Flask, render_template

from .api.v1 import api
from .resume import RESUME_LOCATION, generate_document
from .routes.website import website_blueprint
from .sitemap import sitemap


def create_app():
    app = Flask(__name__)

    app.config.from_pyfile('settings.py')

    app.logger.info("Creating the resume.")
    generate_document(RESUME_LOCATION)
    assert exists(RESUME_LOCATION)
    app.logger.info("Resume Created.")

    app.register_blueprint(website_blueprint)
    app.register_blueprint(api)

    sitemap.init_app(app)

    @app.errorhandler(404)
    def page_not_found(e):
        """HTTP Error 404: Not found."""
        return render_template("error/404.html"), 404

    app.logger.info("Application Created.")
    return app

services/api/website/api/v1/__init__.py
from flask import Blueprint

api = Blueprint('api_v1', __name__, url_prefix='/api/v1')

from .resume import *

services/api/website/routes/website.py
from flask import (Blueprint, abort, escape, redirect, render_template,
                   send_from_directory)
from jinja2.exceptions import TemplateNotFound

from website.connectors.github import GitHubConnector
from website.resources import get_resource_json
from website.resume import RESUME_DIRECTORY_LOCATION, RESUME_FILENAME

website_blueprint = Blueprint(
    'website',
    __name__,
    # NOTE: Relative to blueprints root path
    template_folder='../templates/website',
    static_folder='../static'
)


@website_blueprint.route('/robots.txt', methods=["GET"])
def robots():
    """A file for search engines."""
    return send_from_directory('static/txt', 'robots.txt')


@website_blueprint.route('/', methods=["GET"])
def home():
    """The home route of the website"""

    # Technology, Stars out of 5
    skills = get_resource_json('skills.json')
    technologies = skills['technologies']
    tools = skills['tools']

    # Get career info from JSON file
    careers = get_resource_json('career.json')
    educations = get_resource_json('education.json')
    repos = get_resource_json('repos.json')

    # Sorting lists by number of stars decending
    technologies.sort(key=lambda x: x[1], reverse=True)
    tools.sort(key=lambda x: x[1], reverse=True)

    # Splitting to two columns
    technologies_left = technologies[:len(technologies) // 2]
    technologies_right = technologies[len(technologies) // 2:]
    tools_left = tools[:len(tools) // 2]
    tools_right = tools[len(tools) // 2:]

    # Get my github public info
    github_user_json = GitHubConnector().user

    return render_template('home.html',
                           technologies_left=technologies_left,
                           technologies_right=technologies_right,
                           tools_left=tools_left,
                           tools_right=tools_right,
                           github_user_json=github_user_json,
                           careers=careers,
                           educations=educations,
                           repos=repos)


@website_blueprint.route('/resume', methods=["GET"])
def resume():
    """This route returns a download of my resume."""

    try:
        # return send_from_directory(RESUME_DIRECTORY_LOCATION, path=RESUME_FILENAME, filename=RESUME_FILENAME, as_attachment=True)
        return send_from_directory(RESUME_DIRECTORY_LOCATION, path=RESUME_FILENAME, as_attachment=True)
    except FileNotFoundError:
        abort(404)


@website_blueprint.route('/project/<string:project>', methods=["GET"])
def project(project: str):
    """This route redirects to my github"""

    imagesToPreload = {
        'vitality': ['/static/images/vitality/FrontPage.png',
                     '/static/images/vitality/ShowTrainers.png',
                     '/static/images/vitality/Diets.png',
                     '/static/images/vitality/Workouts.png'],
        'santosderek': ['/static/images/santosderek/santosderekDeployment.png']
    }

    try:
        project = escape(project)

        images = ['/static/images/santosderek.png']
        if project in imagesToPreload:
            images += imagesToPreload[project]

        return render_template(f'project/{project}.html', imagesToPreload=images)
    except TemplateNotFound:
        abort(404)


@website_blueprint.route('/github', methods=["GET"])
def github():
    """This route redirects to my github"""
    return redirect('https://github.com/santosderek')


@website_blueprint.route('/linkedin', methods=["GET"])
def linkedin():
    """This route redirects to my linkedin"""
    return redirect('https://www.linkedin.com/in/santosderek/')

services/api/website/sitemap/__init__.py
from flask_sitemap import Sitemap


sitemap = Sitemap()


from .website import *

services/api/website/templates/website/base.html
<!doctype html>
<html lang="en">

{% include 'head.html' %}

<body id="my-scrollbar">
    <header>
        {% include 'navbar.html'%}
        <!-- Block for child templates to use for additional header statements -->
        {% block inherited_header %}{% endblock %}
    </header>
    <main>
        <div style="display: none;" id="content">
            <div style="display: none;" id="pageLocationScrollSpy" class="list-group">
                <a class="list-group-item list-group-item-action" href="#experience">Experience</a>
                <a class="list-group-item list-group-item-action" href="#skills">Skills</a>
                <a class="list-group-item list-group-item-action" href="#projects">Projects</a>
                <a class="list-group-item list-group-item-action" href="#resume">Resume</a>
                <a class="list-group-item list-group-item-action" href="#contact">Contact</a>
            </div>
            <div data-spy="scroll" data-target="#pageLocationScrollSpy" data-offset="0" class="scrollspy">
                {% block content %}{% endblock %}
            </div>
        </div>
        <div id="loading" class="row" style="min-height: 80vh;">
            <div class="my-auto text-center">
                <p>LOADING</p>
                <div class="spinner-border text-success" role="status">
                    <span class="sr-only">Loading...</span>
                </div>
            </div>
        </div>
    </main>
    <script>
        imagesToPreload = ['/static/images/santosderek.png'];
        window.addEventListener("load", () => {
            preload(imagesToPreload);
            enableScrollSpy();
            revealContent(imagesToPreload);
        }, false);
    </script>
</body>

</html>

services/api/website/templates/website/head.html
<head>
    <meta charset="utf-8">
    <title>Derek Santos</title>
    <meta name="description" content="Derek Santos Portfolio">
    <meta name="author" content="Derek Santos">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <link rel="preload" href="{{ url_for ('static', filename='css/base.css')}}" as="style">
    <link rel="preload" href="{{ url_for('static', filename='js/base.js') }}" as="script">

    <link rel="shortcut icon" type="image/jpg" href="{{url_for('static', filename='images/initials/initials.ico')}}" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
        integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx"
        crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/f08705750d.js" crossorigin="anonymous"></script>
    <link type="text/css" rel="stylesheet" href="{{ url_for ('static', filename='css/base.css')}}">
    <script src="{{ url_for('static', filename='js/base.js') }}"></script>

    <!-- Google Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=VT323&display=swap" rel="stylesheet">
</head>

services/api/website/templates/website/home.html
{% extends 'base.html' %}
{% block inherited_header %}
<link rel="stylesheet" href="{{url_for('static', filename='css/terminal.css')}}">
{% endblock %}

{% block content %}

<section class="terminal-section">
    <div class="terminal">
        <div class="terminal-header">
            <nav class="terminal-header-buttons">
                <span class="control-item control-minimize">‒</span>
                <span class="control-item control-maximize">□</span>
                <span class="control-item control-close">˟</span>
            </nav>
        </div>
        <main class="terminal-body">
            <div class="window-cursor">
                <span class="i-cursor-indicator">> who -u | pixelify</span>
            </div>
            <div class="terminal-flex-container">
                <div class="terminal-flex-item-1 terminal-body-header">
                    <p>Derek Santos</p>
                </div>
                <div class="terminal-flex-item-2 terminal-body-description">
                    <p>A software developer with a passion for automation and orchestration.</p>
                    <p><span>Title:</span> Full-Stack Software Engineer</p>
                    <p><span>Coding Experience:</span> 10+ years</p>
                    <p><span>Passions:</span> Python, Rust, MicroServices</p>
                </div>
            </div>
            <div class="window-cursor">
                <span class="i-cursor-indicator">></span>
                <span class="i-cursor-underscore">_</span>
            </div>
        </main>
    </div>
</section>

<div class="content pt-3">
    <div class="jumbotron pl-5">
        <h1 class="display-4 text-center" id="experience">Experience</h1>
        <p class="lead text-center">"The only way to know how strong you are is to keep testing your limits." – Jor El
        </p>
    </div>

    <div class="row">
        <div class="col">
            <h2>Career</h2>
        </div>
    </div>

    {% for career in careers %}
    <div class="row career">
        <div class="col-md-12 col-lg-4 career_header">
            <h3>{{career['title']}}</h3>
            {% if "type" in career %}
            <p>{{career['type']}}</p>
            {% endif %}
            <p>{{career['date']}}</p>
            <p>{{career['location']}}</p>
        </div>
        <div class="col-md-12 col-lg-8 career_description">
            <ul>
                {% for description in career['descriptions'] %}
                <li>{{ description }}</li>
                {% endfor %}
            </ul>
        </div>
    </div>
    {% endfor %}

    <hr />
    <div class="row">
        <div class="col">
            <h2>Education</h2>
        </div>
    </div>

    {% for education in educations %}
    <div class="row education">
        <div class="col-sm-12 col-lg-4">
            <h3>{{education['title']}}</h3>
            <p>{{education['date']}}</p>
        </div>
        <div class="col-sm-12 col-lg-8 education_description">
            <p><b>{{education['degree']}}</b></p>
            <p><em>Relevant Courses:</em></p>
            <ul>
                {% for course in education['relevantCourses'] %}
                <li>{{course}}</li>
                {% endfor %}
            </ul>

            {% for addition in education['additional'] %}
            <p>{{addition}}</p>
            {% endfor %}
        </div>
    </div>
    {% endfor %}

    <div class="jumbotron pl-5">
        <h1 class="display-4 text-center" id="skills">Skills</h1>
        <p class="lead text-center">"Power! Unlimited power!" - Darth Sidious</p>
    </div>

    <div class="row">
        <div class="col-sm-12 col-md-12">
            <h2><b>Technologies</b></h2>
        </div>
        <div class="col-sm-6 col-lg-6">
            <table class="table table-hover">
                <tbody>
                    {% for entry in technologies_left%}
                    <tr>
                        <td class="skill_title" scope="row">
                            <span>
                                {{entry[0]}}
                            </span>
                        </td>
                        <td class="skill_stars">
                            <span>
                                {% for _ in range(entry[1]) %}
                                <i style="font-size: .5em;" class="fas fa-star"></i>
                                {% endfor %}
                                {% for _ in range(5 - entry[1]) %}
                                <i style="font-size: .5em;" class="far fa-star"></i>
                                {% endfor %}
                            </span>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="col-sm-6 col-lg-6">
            <table class="table table-hover">
                <tbody>
                    {% for entry in technologies_right%}
                    <tr>
                        <td class="skill_title" scope="row">
                            <span>
                                {{entry[0]}}
                            </span>

                        </td>
                        <td class="skill_stars">
                            <span>
                                {% for _ in range(entry[1]) %}
                                <i style="font-size: .5em;" class="fas fa-star"></i>
                                {% endfor %}
                                {% for _ in range(5 - entry[1]) %}
                                <i style="font-size: .5em;" class="far fa-star"></i>
                                {% endfor %}
                            </span>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    <hr />
    <div class="row">
        <div class="col-sm-12">
            <h2><b>Tools</b></h2>
        </div>
        <div class="col-sm-6">
            <table class="table table-hover">
                <tbody>
                    {% for entry in tools_left%}
                    <tr>
                        <td class="skill_title" scope="row">
                            <span>
                                {{entry[0]}}
                            </span>
                        </td>
                        <td class="skill_stars">
                            <span>
                                {% for _ in range(entry[1]) %}
                                <i style="font-size: .5em;" class="fas fa-star"></i>
                                {% endfor %}
                                {% for _ in range(5 - entry[1]) %}
                                <i style="font-size: .5em;" class="far fa-star"></i>
                                {% endfor %}
                            </span>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="col-sm-6">
            <table class="table table-hover">
                <tbody>
                    {% for entry in tools_right%}
                    <tr>
                        <td class="skill_title" scope="row">
                            <span>
                                {{entry[0]}}
                            </span>
                        </td>
                        <td class="skill_stars">
                            <span>
                                {% for _ in range(entry[1]) %}
                                <i style="font-size: .5em;" class="fas fa-star"></i>
                                {% endfor %}
                                {% for _ in range(5 - entry[1]) %}
                                <i style="font-size: .5em;" class="far fa-star"></i>
                                {% endfor %}
                            </span>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

    <div class="jumbotron pl-5">
        <h1 class="display-4 text-center" id="projects">Projects</h1>
        <p class="lead text-center">"Do. Or do not. There is no try." - Yoda</p>

    </div>
    <div class="row">
        {% for repo in repos %}
        <a href="{{repo['url']}}">
            <div class="card mb-3" style="max-width: 18rem;">
                <div class="card-header">{{repo['title']}}</div>
                <div class="card-body">
                    <h5 class="card-title">{{repo['subtitle']}}</h5>
                    <p class="card-text">{{repo['description']}}</p>
                </div>
            </div>
        </a>
        {% endfor %}

        <div class="col-sm-12 text-center mt-4 mb-5">
            <a class="button_link" href="{{ url_for('website.github')}}">
                {% if github_user_json|length == 0 %}
                ...and many more!
                {% else %}
                ...and {{ github_user_json['public_repos'] }} more on github!
                {% endif %}
            </a>
        </div>
    </div>

    <div class="jumbotron pl-5">
        <h1 class="display-4 text-center" id="resume">Resume</h1>
        <p class="lead text-center">"The Force will be with you. Always." - Obi-Wan Kenobi</p>
    </div>

    <div class="row text-center">
        <div class="col-sm-12 col-md-12">
            <p>
                My resume is automated to be created based on the contents of this website.<br />Upon clicking the download
                button on <b>either the top right of the navbar</b>, going to <b><a href="{{url_for('website.resume')}}">
                        {{url_for('website.resume')}} </a></b>, or <b><a href="{{url_for('website.resume')}}">clicking here</a></b>, the
                Flask application (this website) will generate a formatted Microsoft Word file and send the file to your
                computer. This will ensure you always get the most up-to-date version of my resume.
            </p>
        </div>
    </div>

    <div class="jumbotron pl-5">
        <h1 class="display-4 text-center" id="contact">Contact</h1>
        <p class="lead text-center">"And my axe!" - Gimli</p>

    </div>

    <div class="row text-center">
        <div class="col-sm-12 col-md-12">
            <p>The best way to contact me is through email or linkedin!</p>
            <a href="mailto:santos.jon.derek@gmail.com">
                <img style="width: 1.5em; filter: invert(17%) sepia(0%) saturate(1641%) hue-rotate(158deg) brightness(96%) contrast(93%);"
                    src="{{ url_for('website.static', filename='images/svg/envelope.svg') }}" />
                <span>santos.jon.derek@gmail.com</span>
            </a>
            <br />
            <a href="https://www.linkedin.com/in/santosderek/">
                <img style="width: 1.5em; filter: invert(17%) sepia(0%) saturate(1641%) hue-rotate(158deg) brightness(96%) contrast(93%);"
                    src="{{ url_for('website.static', filename='images/svg/linkedin.svg') }}" />
                <span>https://www.linkedin.com/in/santosderek/</span>
            </a>
        </div>
    </div>
    <div class="row" id="justsomespace">
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
    </div>
</div>

{% endblock %}

services/api/website/templates/website/navbar.html
<nav class="navbar navbar-expand-lg my-auto">
    <div class="navbar-collapse collapse w-100 order-1 order-lg-0 dual-collapse2">
        <ul class="navbar-nav m-auto">
            <!-- Left of brand if I need it-->
            <li class="nav-item">
                <a style="padding-right: .5em;" href="{{url_for('website.home') + '#experience'}}">Experience</a>
            </li>
            <li class="nav-item">
                <a style="padding-right: .5em;" href="{{url_for('website.home') + '#skills'}}">Skills</a>
            </li>
            <li class="nav-item">
                <a style="padding-right: .5em;" href="{{url_for('website.home') + '#projects'}}">Projects</a>
            </li>
            <li class="nav-item">
                <a style="padding-right: .5em;" href="{{url_for('website.home') + '#resume'}}">Resume</a>
            </li>
            <li class="nav-item">
                <a href="{{url_for('website.home') + '#contact'}}">Contact</a>
            </li>
        </ul>
    </div>
    <div class="mx-auto order-0">
        <a class="navbar-brand mx-auto" href="/" style="font-size: xx-large;">
            <img src="{{ url_for('website.static', filename='images/santosderek.png')}}" alt="Derek Santos" />
        </a>
        <button class="navbar-toggler ml-3" type="button" data-toggle="collapse" data-target=".dual-collapse2">
            <span class="navbar-toggler-icon"></span>
        </button>
    </div>
    <div class="navbar-collapse collapse w-100 order-3 dual-collapse2">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('website.github')}}">
                    <img style="width: 1.5em; filter: invert(17%) sepia(0%) saturate(1641%) hue-rotate(158deg) brightness(96%) contrast(93%);"
                        src="{{ url_for('website.static', filename='images/svg/github.svg') }}" />
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('website.linkedin')}}">
                    <img style="width: 1.5em; filter: invert(17%) sepia(0%) saturate(1641%) hue-rotate(158deg) brightness(96%) contrast(93%);"
                        src="{{ url_for('website.static', filename='images/svg/linkedin.svg') }}" />
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="mailto:santos.jon.derek@gmail.com">
                    <img style="width: 1.5em; filter: invert(17%) sepia(0%) saturate(1641%) hue-rotate(158deg) brightness(96%) contrast(93%);"
                        src="{{ url_for('website.static', filename='images/svg/envelope.svg') }}" />
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('website.resume') }}">
                    <img style="width: 1.5em; filter: invert(17%) sepia(0%) saturate(1641%) hue-rotate(158deg) brightness(96%) contrast(93%);"
                        src="{{ url_for('website.static', filename='images/svg/download.svg') }}" />
                </a>
            </li>
        </ul>
    </div>
</nav>

services/api/website/templates/website/project/project.html
<!doctype html>
<html lang="en">

{% include 'head.html' %}

<body>
    <header>
        {% include 'navbar.html'%}
    </header>
    <main>
        <div style="display: none;" id="content">
            {% block content %}{% endblock %}
        </div>
        <div id="loading" class="row" style="min-height: 80vh;">
            <div class="my-auto text-center">
                <p>LOADING</p>
                <div class="spinner-border text-success" role="status">
                    <span class="sr-only">Loading...</span>
                  </div>
            </div>
        </div>
    </main>
    
    <script>
        imagesToPreload = {{imagesToPreload|safe}};
        window.addEventListener("load", () => {
            preload(imagesToPreload);
            revealContent(imagesToPreload);
        }, false);
    </script>
</body>

</html>

services/api/website/templates/website/project/santosderek.html
{% extends 'project/project.html' %}

{% block content %}


<div class="row mt-4">
    <div class="col-sm-12 col-md-12 col-lg-12 mt-3 text-center">
        <h1>SantosDerek.com</h1>
        <p class="w-50">
            My personal website and dynamic resume.
        </p>
    </div>
</div>


<div class="row project_overview">
    <div class="col-sm-12 text-center">
        <h3>Project Overview</h3>
    </div>
    <div class="pt-4 col-sm-12 col-md-12">
        <p class="w-75">In order to showcase my projects and experience using specific technologies, I have decided to
            create a resource where users may view an overview of my latest achievements. This website is also a project
            within itself since all aspects of the website was created using Python, Docker, Github Actions, and
            Ansible. Below is a dive into the work, and features this website holds under the hood as well as the
            deployment of the website itself.</p>
    </div>
</div>


<div class="row project_overview">
    <div class="col-sm-12 text-center">
        <h3>A Dynamic Home Page</h3>
    </div>
    <div class="pt-4 col-sm-12 col-md-12">
        <p class="w-75">Due to the nature of using Flask as a web framework, Jinja is used as the default templating
            solution for webpages. The landing page of the application is built and populated by two major templates;
            base.html and home.html which can be viewed within the GitHub repository. Home.html extends the base.html
            template and populates the page using data declared within the home route's declared function within the
            Flask application factory, i.e. __init__.py. This allows me to have a general format for the page, but
            dynamically populate the contents by importing the data into the rendered template at each request.</p>

        <p class="w-75">The data is organized and parsed from a series of JSON files found within the resources folder
            of the repository. These files are read, parsed into python lists and dictionaries, and sent to the view.
            When updating the home page of my website, I only need to add or remove entries within these JSON files, and
            the contents of the page should adjust automatically on the next request.</p>
    </div>
</div>

<div class="row project_overview">
    <div class="col-sm-12 text-center">
        <h3>Automatic Resume Creator</h3>
    </div>
    <div class="pt-4 col-sm-12 col-md-12">
        <p class="w-75">Upon runtime of the web application, the JSON resource files are used to create a structured and
            styled Word Document entirely using the python-docx module. This Word Document is the very same file given
            when visiting <b><a href="{{ url_for('website.resume')}}">/resume</a></b> route.</p>
        <p class="w-75"></p>
    </div>
</div>

<div class="row project_overview">
    <div class="col-sm-12 text-center">
        <h3>Deployment Architecture</h3>
    </div>
    <div class="pt-4 col-sm-12 col-md-12 text-center">
        <img class="w-75" src="{{url_for('website.static', filename='images/santosderek/santosderekDeployment.png')}}"
            alt="Santosderek deployment" />
    </div>
    <div class="pt-4 col-sm-12 col-md-12">
        <p class="w-75">The deployment process of the website involves the usage of Github, Github Actions, a
            DigitalOcean, Ansible, and Docker. When committing changes, I push the respective commits to Github where
            upon creating a pull request will trigger a workflow to verify all unit tests pass. The workflow also
            verifies and build the Dockerfile to be deployed. After all checks pass, I accept the pull request and first
            deploy the updated Docker image to a test environment within my homelab using Ansible. Once my inspection is
            complete within the test environment, I run a second Ansible script which deploys the code to the Digital
            Ocean droplet, updating the docker image to the most recent change, and serves the flask application
            through santosderek.com.</p>
    </div>
</div>

<div class="row mt-3">
    <div class="col-sm-12 col-md-6 mt-3 text-center">
        <h2 style="padding-bottom: 1em;">Github</h2>
        <a href="https://github.com/santosderek/website" class="button_link">View the source on github!</a>
    </div>
</div>

{% endblock %}